// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1QolLoAtSo4Nb33tMNjOZx2aZ0bE74M',
    appId: '1:266213269942:web:1327152fdeca69b150a117',
    messagingSenderId: '266213269942',
    projectId: 'uploadbackgroundapp',
    authDomain: 'uploadbackgroundapp.firebaseapp.com',
    storageBucket: 'uploadbackgroundapp.appspot.com',
    measurementId: 'G-FXYZDDFCW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pVuzGZyFr5Orq-SDZan5wjammmWd-L0',
    appId: '1:266213269942:android:f4b0e47a4dcc660d50a117',
    messagingSenderId: '266213269942',
    projectId: 'uploadbackgroundapp',
    storageBucket: 'uploadbackgroundapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsklptEl15K2yhdyt5a2ZofJEB8Me-Lg',
    appId: '1:266213269942:ios:f7ad1038cceb2c4750a117',
    messagingSenderId: '266213269942',
    projectId: 'uploadbackgroundapp',
    storageBucket: 'uploadbackgroundapp.appspot.com',
    iosBundleId: 'com.example.uploadBackgroundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPsklptEl15K2yhdyt5a2ZofJEB8Me-Lg',
    appId: '1:266213269942:ios:fd418bedfdc1186a50a117',
    messagingSenderId: '266213269942',
    projectId: 'uploadbackgroundapp',
    storageBucket: 'uploadbackgroundapp.appspot.com',
    iosBundleId: 'com.example.uploadBackgroundApp.RunnerTests',
  );
}
